<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-21T22:04:00 ICT" name="Default suite" finished-at="2023-05-21T22:04:42 ICT" duration-ms="41471">
    <groups>
    </groups>
    <test started-at="2023-05-21T22:04:00 ICT" name="Default test" finished-at="2023-05-21T22:04:42 ICT" duration-ms="41471">
      <class name="TestCase.EndToEnd">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestCase.EndToEnd@595b007d]" started-at="2023-05-21T22:04:00 ICT" name="setUp" finished-at="2023-05-21T22:04:11 ICT" duration-ms="10817" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="EndToEndTC()[pri:0, instance:TestCase.EndToEnd@595b007d]" started-at="2023-05-21T22:04:11 ICT" name="EndToEndTC" finished-at="2023-05-21T22:04:41 ICT" duration-ms="29894" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at TestCase.EndToEnd.EndToEndTC(EndToEnd.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndToEndTC -->
        <test-method is-config="true" signature="CaptureAndAttact(org.testng.ITestResult)[pri:0, instance:TestCase.EndToEnd@595b007d]" started-at="2023-05-21T22:04:41 ICT" name="CaptureAndAttact" finished-at="2023-05-21T22:04:42 ICT" duration-ms="237" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=EndToEndTC status=FAILURE method=EndToEnd.EndToEndTC()[pri:0, instance:TestCase.EndToEnd@595b007d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CaptureAndAttact -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCase.EndToEnd@595b007d]" started-at="2023-05-21T22:04:42 ICT" name="tearDown" finished-at="2023-05-21T22:04:42 ICT" duration-ms="454" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCase.EndToEnd -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
